#for custom plugins contact my discord: ShaneDragonDev#7887
#join our discord server code: r446jHY
#xxcauldevsxx is a fake ass developer he stole all my code and wants to now claim it has his own
keep-out-message: "You Cant Enter Spawn In Combat"
combat-cooldown: 0
